# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Main builds
  - board: nice_nano_v2
    shield: dasbob_main_left

  - board: nice_nano_v2
    shield: dasbob_main_right

  # Dongle builds
  - board: nice_nano_v2
    shield: dasbob_dongle_central
    # snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: dasbob_dongle_left

  - board: nice_nano_v2
    shield: dasbob_dongle_right

  # Settings reset
  - board: nice_nano_v2
    shield: settings_reset
