version: '3.8'

services:
  zmk-build:
    image: zmkfirmware/zmk-build-arm:3.5-branch
    volumes:
      - zmk-workspace:/zmk-workspace # named volume for persistence
      - ./zmk-out:/zmk-out
      - ./zmk-bin:/zmk-bin
      - ./zmk-config:/zmk-config
      - ./build.yaml:/zmk-build.yaml
    environment:
      - CMAKE_PREFIX_PATH=/zmk-workspace
    working_dir: /zmk-workspace
    tty: true
    entrypoint: /bin/bash

volumes:
  zmk-workspace:
    name: zmk-workspace
