manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: MuneebBaderoen
      url-base: https://github.com/MuneebBaderoen
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      clone-depth: 1
      import: app/west.yml
    - name: zmk-tri-state
      remote: MuneebBaderoen
      revision: main
      clone-depth: 1
    - name: zmk-magic-key
      remote: MuneebBaderoen
      revision: main
      clone-depth: 1
  self:
    path: .
